### ISSUE TITLE
Patch for /downloader.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yousef4630/webmaster-tools-downloads#10]
```
.......
```

Original issue reported on code.google.com by `majidjam...@gmail.com` on 16 Dec 2014 at 12:08

Attachments:
- [downloader.py.patch](https://storage.googleapis.com/google-code-attachments/webmaster-tools-downloads/issue-10/comment-0/downloader.py.patch)

**Comment by yousef4630** [comment]
طباعة (202 \* 2)؛ للخروج ()؛
