### ISSUE TITLE
Patch for /example-create-spreadsheet.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yousef4630/webmaster-tools-downloads#4]
```
From my experience, if you use proposed source code in Python 2.x it will 
return 'invalid syntax' error. In a case you're using Python 3.x change the 
54th line.
```

Original issue reported on code.google.com by `agent.ju...@gmail.com` on 26 Jan 2012 at 1:09

Attachments:
- [example-create-spreadsheet.py.patch](https://storage.googleapis.com/google-code-attachments/webmaster-tools-downloads/issue-4/comment-0/example-create-spreadsheet.py.patch)

**Comment by yousef4630** [comment]
dougwal ... @ searchometry.com
